In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.cross_validation import train_test_split as tts
import operator

In [3]:
dataset = pd.read_csv('zoo.csv')

dataset

animal name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0      aardvark     1         0     0     1         0        0         1   
1      antelope     1         0     0     1         0        0         0   
2          bass     0         0     1     0         0        1         1   
3          bear     1         0     0     1         0        0         1   
4          boar     1         0     0     1         0        0         1   
5       buffalo     1         0     0     1         0        0         0   
6          calf     1         0     0     1         0        0         0   
7          carp     0         0     1     0         0        1         0   
8       catfish     0         0     1     0         0        1         1   
9          cavy     1         0     0     1         0        0         0   
10      cheetah     1         0     0     1         0        0         1   
11      chicken     0         1     1     0         1        0         0   
12         chub     0         0     1     0         0        1         1   
13         clam     0         0     1     0         0        0         1   
14         crab     0         0     1     0         0        1         1   
15     crayfish     0         0     1     0         0        1         1   
16         crow     0         1     1     0         1        0         1   
17         deer     1         0     0     1         0        0         0   
18      dogfish     0         0     1     0         0        1         1   
19      dolphin     0         0     0     1         0        1         1   
20         dove     0         1     1     0         1        0         0   
21         duck     0         1     1     0         1        1         0   
22     elephant     1         0     0     1         0        0         0   
23     flamingo     0         1     1     0         1        0         0   
24         flea     0         0     1     0         0        0         0   
25         frog     0         0     1     0         0        1         1   
26         frog     0         0     1     0         0        1         1   
27     fruitbat     1         0     0     1         1        0         0   
28      giraffe     1         0     0     1         0        0         0   
29         girl     1         0     0     1         0        0         1   
..          ...   ...       ...   ...   ...       ...      ...       ...   
71         rhea     0         1     1     0         0        0         1   
72     scorpion     0         0     0     0         0        0         1   
73     seahorse     0         0     1     0         0        1         0   
74         seal     1         0     0     1         0        1         1   
75      sealion     1         0     0     1         0        1         1   
76     seasnake     0         0     0     0         0        1         1   
77      seawasp     0         0     1     0         0        1         1   
78      skimmer     0         1     1     0         1        1         1   
79         skua     0         1     1     0         1        1         1   
80     slowworm     0         0     1     0         0        0         1   
81         slug     0         0     1     0         0        0         0   
82         sole     0         0     1     0         0        1         0   
83      sparrow     0         1     1     0         1        0         0   
84     squirrel     1         0     0     1         0        0         0   
85     starfish     0         0     1     0         0        1         1   
86     stingray     0         0     1     0         0        1         1   
87         swan     0         1     1     0         1        1         0   
88      termite     0         0     1     0         0        0         0   
89         toad     0         0     1     0         0        1         0   
90     tortoise     0         0     1     0         0        0         0   
91      tuatara     0         0     1     0         

In [4]:
dataset.shape

(101, 18)

In [5]:
dataset.isnull().sum() #Verifica se possui valor nulo

animal name    0
hair           0
feathers       0
eggs           0
milk           0
airborne       0
aquatic        0
predator       0
toothed        0
backbone       0
breathes       0
venomous       0
fins           0
legs           0
tail           0
domestic       0
catsize        0
type           0
dtype: int64

In [6]:
dataset = dataset.drop('animal name',axis=1) #Exclui a coluna 'animal name'

In [7]:
dataset['legs'] = dataset['legs'].astype(float)

In [8]:
predictors = dataset.iloc[:,:16].values #Seleciona as colunas p/ previsores

predictors

array([[1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 1.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 1., 0., 0.]])

In [9]:
classe = dataset.iloc[:,16].values #Seleciona a coluna classe

classe

array([1, 1, 4, 1, 1, 1, 1, 4, 4, 1, 1, 2, 4, 7, 7, 7, 2, 1, 4, 1, 2, 2,
       1, 2, 6, 5, 5, 1, 1, 1, 6, 1, 1, 2, 4, 1, 1, 2, 4, 6, 6, 2, 6, 2,
       1, 1, 7, 1, 1, 1, 1, 6, 5, 7, 1, 1, 2, 2, 2, 2, 4, 4, 3, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 7, 4, 1, 1, 3, 7, 2, 2, 3, 7, 4, 2, 1, 7, 4, 2,
       6, 5, 3, 3, 4, 1, 1, 2, 1, 6, 1, 7, 2], dtype=int64)

In [10]:
escaler = MinMaxScaler() #Escalonamento

In [11]:
predictors[:, 12] = escaler.fit_transform(predictors[:, 12:13]).T

predictors[:, 12] 

array([0.5  , 0.5  , 0.   , 0.5  , 0.5  , 0.5  , 0.5  , 0.   , 0.   ,
       0.5  , 0.5  , 0.25 , 0.   , 0.   , 0.5  , 0.75 , 0.25 , 0.5  ,
       0.   , 0.   , 0.25 , 0.25 , 0.5  , 0.25 , 0.75 , 0.5  , 0.5  ,
       0.25 , 0.5  , 0.25 , 0.75 , 0.5  , 0.25 , 0.25 , 0.   , 0.5  ,
       0.5  , 0.25 , 0.   , 0.75 , 0.75 , 0.25 , 0.75 , 0.25 , 0.5  ,
       0.5  , 0.75 , 0.5  , 0.5  , 0.5  , 0.5  , 0.75 , 0.5  , 1.   ,
       0.5  , 0.5  , 0.25 , 0.25 , 0.25 , 0.25 , 0.   , 0.   , 0.   ,
       0.5  , 0.5  , 0.5  , 0.   , 0.5  , 0.5  , 0.5  , 0.5  , 0.25 ,
       1.   , 0.   , 0.   , 0.25 , 0.   , 0.   , 0.25 , 0.25 , 0.   ,
       0.   , 0.   , 0.25 , 0.25 , 0.625, 0.   , 0.25 , 0.75 , 0.5  ,
       0.5  , 0.5  , 0.   , 0.25 , 0.5  , 0.25 , 0.25 , 0.75 , 0.5  ,
       0.   , 0.25 ])

In [12]:
predictors

array([[1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 1.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 1., 0., 0.]])

In [13]:
predictors.shape

(101, 16)

In [14]:
#Criação dos modelos de treinamento e de teste
trainset_X, testset_X, trainset_Y, testset_Y = tts(predictors, classe, test_size = 0.25, random_state = 0)

In [15]:
print(trainset_X.shape)
print(testset_X.shape)


(75, 16)
(26, 16)


In [16]:
rows, columns = trainset_X.shape
aux = np.zeros((rows, columns+1))
aux[:,:-1] = trainset_X
aux[:,-1] = trainset_Y
trainset = aux
trainset.shape

(75, 17)

In [17]:
rows, colunms = testset_X.shape
aux = np.zeros((rows, columns+1))
aux[:,:-1] = testset_X
aux[:,-1] = testset_Y
testset = aux
testset.shape

(26, 17)

In [18]:
#Cálculo da distância euclidiana
def euclidian_dist(a, b):
    soma = 0
    for i in range(len(a)-1):
        soma += (a[i] - b[i])**2
    return soma **(1/2)

In [19]:
#Implementação KNN
def getNeighbors(trainset, test, k):
    d = []
    neighbors = []
    for i in range(len(trainset)):
        #Calcula a distância
        euclidian_d = euclidian_dist(test, trainset[i])
        #Lista com a instância do conjunto de treino e sua distância da instância dada
        d.append((trainset[i], euclidian_d))
    #Ordenação colocando os mais próximos no começo
    d.sort(key=operator.itemgetter(1))
    #Armazena as k primeiras instâncias
    for j in range(k):
        neighbors.append(d[j][0])
    return neighbors

In [20]:
#Classificação KNN
def classificKNN(neighbors):
    result = {}
    for i in range(len(neighbors)):
        #Pega o ultimo elemento de cada lista que é a classe
        resp = neighbors[i][-1]
        if resp in result:
            result[resp] += 1
        else:
            result[resp] = 1
    resultMax = sorted(result.items(), key=operator.itemgetter(1), reverse=True)
    return resultMax[0][0]

In [21]:
#Calcula a acurácia do modelo
def getAccuracy(testset, predict):
    correct = 0
    for i in range(len(testset)):
        if predict[i] == testset[i][-1]:
            correct += 1
    return (correct/len(testset))*100

In [22]:
k = 13
classification = []
for i in range(len(testset)):
    neighbors = getNeighbors(trainset, testset[i], k)
    result = classificKNN(neighbors)
    classification.append(result)
    print(f'Resultado retornado: {result.astype(int)} | Resultado esperado: {testset[i][-1].astype(int)}')

Resultado retornado: 7 | Resultado esperado: 5
Resultado retornado: 4 | Resultado esperado: 4
Resultado retornado: 4 | Resultado esperado: 4
Resultado retornado: 1 | Resultado esperado: 1
Resultado retornado: 1 | Resultado esperado: 1
Resultado retornado: 1 | Resultado esperado: 1
Resultado retornado: 2 | Resultado esperado: 2
Resultado retornado: 4 | Resultado esperado: 4
Resultado retornado: 1 | Resultado esperado: 1
Resultado retornado: 1 | Resultado esperado: 1
Resultado retornado: 7 | Resultado esperado: 7
Resultado retornado: 1 | Resultado esperado: 1
Resultado retornado: 2 | Resultado esperado: 2
Resultado retornado: 7 | Resultado esperado: 7
Resultado retornado: 4 | Resultado esperado: 4
Resultado retornado: 6 | Resultado esperado: 6
Resultado retornado: 1 | Resultado esperado: 1
Resultado retornado: 7 | Resultado esperado: 6
Resultado retornado: 2 | Resultado esperado: 2
Resultado retornado: 4 | Resultado esperado: 4
Resultado retornado: 2 | Resultado esperado: 2
Resultado ret

In [23]:
accuracy = getAccuracy(testset, classification)
print(f'Acurácia = {accuracy} %')

Acurácia = 92.3076923076923 %
